p8105_hw1_yx2711
================
Yingchen Xu
2022-09-23

# Problem 1

``` r
data("penguins", package = "palmerpenguins")
penguins = penguins
# find number of columns and rows for penguins dataset
ncol(penguins)
```

    ## [1] 8

``` r
nrow(penguins)
```

    ## [1] 344

``` r
# find mean of flipper length
summary(penguins$flipper_length_mm)
```

    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
    ##   172.0   190.0   197.0   200.9   213.0   231.0       2

There are 344 observations and 8 variables in the penguins dataset. The
variables are species, island, bill length, bill depth, flipper length,
body mass, sex and year. There are 8 columns and 344 rows. The mean of
flipper length is 200.9.

``` r
# Make a scatterplot for bill length vs flipper length, which is group by species.
scatterplot = ggplot(data = penguins, aes(x = bill_length_mm, y = flipper_length_mm)) + geom_point() + aes(color = species)

scatterplot
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_yx2711_files/figure-gfm/unnamed-chunk-2-1.png)<!-- -->

``` r
# Save scatterplot
ggsave("scatterplot.pdf")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values (geom_point).

# Problem 2

``` r
# Create a dataframe called df with a random sample of size 10 from a standard Normal distribution, a logical vector, a character vector and a factor vector
df = 
  tibble(
    var_norm = rnorm(n = 10),
    var_log = c(var_norm > 0),
    var_char = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    var_fac = factor(c('low','med','high','low','med','high','low','med','high','low'))
  )

# Use the pull function to calculate the mean of variables in the data frame df.
mean(pull(df, 1))
```

    ## [1] 0.3333067

``` r
mean(pull(df, 2))
```

    ## [1] 0.5

``` r
mean(pull(df, 3))
```

    ## Warning in mean.default(pull(df, 3)): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

``` r
mean(pull(df, 4))
```

    ## Warning in mean.default(pull(df, 4)): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

The calculations of mean works for the random sample from the standard
normal distribution and the logical vector. It does not work for the
character vector and the factor vector.

``` r
as.numeric(pull(df, 2))
as.numeric(pull(df, 3))
as.numeric(pull(df, 4))
```

After converting the variables into numeric type, the logical variable
turns in to a group of 1 and 0.The character variable turns in to a
group of NA, and the factor variable turns in to 1, 2, 3 depending on
its level. When using the pull function to calculate the mean, the
warning suggests that the argument is not numeric or logical. The mean
of logical variable could be calculated because logical variable exists
as 1 or 0. The mean of character variable and factor variable cannot be
calculated because they are not stored as any numeric format.
